### PR TITLE
⚠️ CONFLICT! Lineage pull request for: skeleton

### PR DESCRIPTION
**Pull request by cisagovbot**
# Lineage Pull Request: CONFLICT #

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-python-library.git`](https://github.com/cisagov/skeleton-python-library.git)
Remote branch: `HEAD`

Check the changes in this pull request to ensure they won't cause issues with
your project.

The `lineage/skeleton` branch has **one or more unresolved merge conflicts**
that you must resolve before merging this pull request!

## How to resolve the conflicts ##

1. Take ownership of this pull request by removing any other assignees.

1. Clone the repository locally, and reapply the merge:

    ```console
    git clone git@github.com:cisagov/lcgit.git lcgit
    cd lcgit
    git remote add skeleton https://github.com/cisagov/skeleton-python-library.git
    git remote set-url --push skeleton no_push
    git switch develop
    git checkout -b lineage/skeleton --track origin/develop
    git pull skeleton HEAD
    git status
    ```

1. Review the changes displayed by the `status` command.  Fix any conflicts and
   possibly incorrect auto-merges.

1. After resolving each of the conflicts, `add` your changes to the
   branch, `commit`, and `push` your changes:

    ```console
    git add README.md 
    git commit
    git push --force --set-upstream origin lineage/skeleton
    ```

    Note that you may *append* to the default merge commit message
    that git creates for you, but *please do not delete the existing
    content*.  It provides useful information about the merge that is
    being performed.

1. Wait for all the automated tests to pass.

1. Check the "Everything is cool" checkbox below:

    - [x] ✌️ The conflicts in this pull request have been resolved.

1. Mark this draft pull request "Ready for review".

---

**Note:** *You are seeing this because one of this repository's maintainers has
configured [Lineage] to open pull requests.*

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

### CODE REVIEW

**Comment by jsf9k** [comment]
@felddy - The code as it stands [is failing for Python >= 3.11](https://github.com/cisagov/lcgit/actions/runs/3989474632/jobs/6841949368#step:6:848), because the signature of `random.shuffle` [has](https://docs.python.org/3.10/library/random.html#random.shuffle) [changed](https://docs.python.org/3.11/library/random.html#random.shuffle).  The problem is here:
https://github.com/cisagov/lcgit/blob/3f2fd33c1ac54b7e30a7c655cbe63298e4459160/src/lcgit/lcgit.py#L117-L123

I know it's been a while since you wrote this, but do you have any bright ideas for how to fix it?  One solution would be to modify our code to reproduce whatever the pre-3.11 code was doing, although I think it's worth noting that the `else` clause only applies for `self.seqlength <= 4` which is a case of limited usefulness anyway.

**Comment by felddy** [comment]
I'm delving into the mines to see if I can find a solution.  

From https://github.com/python/cpython/issues/84645

> AFAICT, no one ever uses the optional parameter, nor would they have a valid reason to do so. It is an ancient API oddity and is inconsistent with the other methods in the module. I've long been annoyed by it and would like to see it cleaned-up before I retire ;-)

From https://github.com/pre-commit/pre-commit/issues/1479

> pre-commit uses this to do deterministic shuffling, please don't remove this

Python maintainer's response:
monty-python-john-cleese


See:
- https://github.com/python/cpython/issues/84645
- https://github.com/pre-commit/pre-commit/issues/1479

**Review by jsf9k — APPROVED** [review]

**Comment by jmorrowomni** [comment]
👍

**Review by dav3r — APPROVED** [review]

**Review by felddy — APPROVED** [review]
Looks good. 
Quick question.  What merited the minor version bump vs. just the revision? 
`0.1.0` -> `0.1.1`
`0.1.0` -> `0.2.0`

**Comment by dav3r** [comment]
> Looks good. Quick question. What merited the minor version bump vs. just the revision? `0.1.0` -> `0.1.1` `0.1.0` -> `0.2.0`

I can't find the discussion right now (not sure if it was on GH or in chat), but it's because we added support for Python 3.11 (see https://github.com/cisagov/skeleton-python-library/pull/109).

**Comment by mcdonnnj** [comment]
> 

Just to document my rationale for bumping `minor` over `patch`. Per the [Semantic Versioning Specification](https://semver.org/#spec-item-7):

> Minor version Y (x.Y.z | x > 0) **MUST be incremented if new, backwards compatible functionality is introduced to the public API**. It MUST be incremented if any public API functionality is marked as deprecated. It MAY be incremented if substantial new functionality or improvements are introduced within the private code. It MAY include patch level changes. Patch version MUST be reset to 0 when minor version is incremented.

Emphasis mine. I interpreted explicitly adding support for a new Python version as new, backwards compatible functionality. Also this is why in https://github.com/cisagov/pshtt/pull/235 I **did not** increment the version at all (no Python support changes were made).

**Pull request merged**
